version: 0.0

os: linux

files:
  - source: ./target/ROOT.war
    destination: /opt/tomcat/webapps
  - source: cloudwatch-config.json
    destination: /opt
hooks:
  ApplicationStop:
    - location: ./script/stop.sh 
      timeout: 180
  BeforeInstall:
   - location: ./script/before.sh
     timeout: 180
  AfterInstall:
   - location: ./script/after.sh
     timeout: 180
  ApplicationStart:
    - location: ./script/start.sh
      timeout: 900
 
