name: Upload Website

env:
  ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
  CODEDEPLOY_APP_NAME: csye6225-webapp
  CODEDEPLOY_APP_DEPLOYGROUPNAME: csye6225-webapp-deployment
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        echo "${{ env.ARTIFACT_NAME }}"
        pwd
        ls -al
        mvn -X -B package --file pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

   # - name: Create Deployment
   #   uses: aws deploy create-deployment \
   #         --application-name  \ 
   #         --deployment-config-name your-deployment-config-name \ 
   #         --deployment-group-name your-deployment-group-name \ 
   #         --s3-location bucket=codedeploy.tufekciz,key=WordPressApp.zip,bundleType=zip
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://codedeploy.tufekciz
