name: CI-CD

env:
  ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
  CODEDEPLOY_APP_NAME: csye6225-webapp
  CODEDEPLOY_APP_DEPLOYGROUPNAME: csye6225-webapp-deployment
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        echo "${{ env.ARTIFACT_NAME }}"
        pwd
        ls -al
        mvn -X -B package --file pom.xml -Dmaven.test.skip=true
    - name: Build Deployment Artifact
      run: |
        mkdir codedeploy_artifact
        zip -r ${{ env.ARTIFACT_NAME }} target/demo-0.0.1-SNAPSHOT.war script/*.sh appspec.yml
        mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact/
        ls -al
        pwd
        cd codedeploy_artifact
        pwd
        ls -al
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws --version
        aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_BUCKET_NAME }}

    - name: Create Deployment
      run: |
        aws deploy create-deployment --application-name ${{ env.CODEDEPLOY_APP_NAME }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.CODEDEPLOY_APP_DEPLOYGROUPNAME }} --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=${{ env.ARTIFACT_NAME }},bundleType=zip
